### ISSUE TITLE
在拖动的过程中，上面能显示具体的数字么，就像播放器那样拖动时可以显示时间那样

### ISSUE THREAD

**Issue by hegelsu** [changsanjiang/SJSlider#2]
类似这样：https://github.com/TomThorpe/TTRangeSlider

**Comment by changsanjiang** [comment]
目前没有这个功能, 晚上我抽空加上去吧😁

**Comment by hegelsu** [comment]
现在加上了么？

**Comment by hegelsu** [comment]
只要拖动的时候有就行了，不拖动的时候不用显示

**Comment by changsanjiang** [comment]
好的. 忙的忘记了... 我现在加一下

**Comment by hegelsu** [comment]
辛苦了，有空弄就可以了，不用这么急

**Comment by changsanjiang** [comment]
我加了一个promptLabel.
- 配置一下label
```objective-c
    slider3.promptLabel.textColor = [UIColor whiteColor];
    slider3.promptLabel.font = [UIFont boldSystemFontOfSize:14];
    slider3.promptSpacing = 6; 
```

- 代理方法控制显示或者隐藏
```objective-c
- (void)sliderWillBeginDragging:(SJSlider *)slider {
    slider.promptLabel.hidden = NO;
    slider.promptLabel.text = [NSString stringWithFormat:@"%.02f", slider.value];
}

- (void)sliderDidDrag:(SJSlider *)slider {
    slider.promptLabel.text = [NSString stringWithFormat:@"%.02f", slider.value];
}

- (void)sliderDidEndDragging:(SJSlider *)slider {
    slider.promptLabel.hidden = YES;
}
```

**Comment by changsanjiang** [comment]
这样可以吗?

**Comment by hegelsu** [comment]
要看下具体效果才好说，另外不知道有没有这个功能，就是比如拿这个控件做播放进度条，可能需要这样一个功能，就是我直接点到某个点，那么就需要跳到那个点，也就是说我不拖，我直接点进度条后面的区域来快速跳到那里

**Comment by changsanjiang** [comment]
提示功能我推上去了.  另外跳转功能, 我再加一下.  还有其他的功能需求吗?

**Comment by hegelsu** [comment]
目前没有了，非常感谢

**Comment by changsanjiang** [comment]
额, 关于点击的功能, 是点击到轨道上呢? 还是整个slider?
![image](https://user-images.githubusercontent.com/25744224/42011726-6388702c-7ac7-11e8-8433-e6fb804cf94b.png)

**Comment by changsanjiang** [comment]
最大的灰色部分是整个slider,  较亮的灰色部分是 轨道

**Comment by hegelsu** [comment]
绿色以及绿色后面的那段灰色的区域都可以点，点到哪这个圆点就跳到哪，类似于播放器进度条的那种操作

**Comment by changsanjiang** [comment]
这样子的话有个问题就是 轨道很细的话, 很难点到了

**Comment by changsanjiang** [comment]
我先做完吧, 看效果吧

**Comment by hegelsu** [comment]
我明白你说的意思了，那如果是这样的话感觉是整个区域点击接受事情才合理一些

**Comment by changsanjiang** [comment]
跳转也加上了, 不过需要开启一下手势. (默认是关闭的)

```objective-c
slider.tap.enable = YES;
```

![image](https://user-images.githubusercontent.com/25744224/42012021-d39a6a9a-7ac8-11e8-92a4-20f7634deb40.png)

**Comment by hegelsu** [comment]
好的，谢谢
